spring:
  main:
    web-application-type: none
  jmx.enabled: false
  datasource:
    write:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/job?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: one_dev
      password: one_dev
      type: com.zaxxer.hikari.HikariDataSource
      maximum-pool-size: 10
    read1:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/java_camp_demo_a?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: one_dev
      password: one_dev
      type: com.zaxxer.hikari.HikariDataSource
      maximum-pool-size: 5
    read2:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/java_camp_demo_b?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: one_dev
      password: one_dev
      type: com.zaxxer.hikari.HikariDataSource
      maximum-pool-size: 5
